dist: bionic
language: python
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
services:
  - docker


before_install:
  - docker pull ubuntu:bionic

jobs:
  include:
  - stage: build
    script:
     - make tux_pkg
     - make win_pkg
    if: tag IS blank
  - stage: release to github
    script: 
     - echo "Deploying to github..."
     - VER=$TRAVIS_TAG make tux_pkg
     - VER=$TRAVIS_TAG make win_pkg
    if: tag IS present
    deploy:
      provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      skip_cleanup: true
      file_glob: true
      file:
        - electron_build/dist/emptyorch_linux.AppImage
        - electron_build/dist/emptyorch_win.exe
      on:
        tags: true
        repo: kubilus1/emptyorchestra
