dist: bionic
language: python
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
services:
  - docker


before_install:
  - docker pull ubuntu:bionic

jobs:
  include:
  - stage: build
    script:
     - make tux_pkg
     - make win_pkg
    if: tag IS blank
  - stage: release to github
    script: 
     - echo "Deploying to github..."
     - VER=$TRAVIS_TAG make packages
    if: tag IS present
    deploy:
      provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      skip_cleanup: true
      file_glob: true
      file:
        - dist/electron_build/emptyorch-*.AppImage
        - dist/electron_build/emptyorch*.exe
      on:
        tags: true
        repo: kubilus1/emptyorchestra
