theme: jekyll-theme-architect
show_downloads: true
title: Emptyorchestra
github:
  win_url: https://github.com/kubilus1/emptyorchestra/releases/latest/download/emptyorch.exe
  linux_url: https://github.com/kubilus1/emptyorchestra/releases/latest/download/emptyorch_amd64_linux
