FROM ubuntu:xenial

RUN apt-get update && apt-get install -y python3 python3-pip
RUN python3 -m pip install -U pip
RUN python3 -m pip install pyinstaller
RUN apt-get update && apt-get install -y libpng16-16 libssh-gcrypt-4 python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.0
