# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcemptyorch_frame(wx.Frame):
#!XRCED:begin-block:xrcemptyorch_frame.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcemptyorch_frame.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "emptyorch_frame")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_MENU, self.OnMenu_open_menu, id=xrc.XRCID('open_menu'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_choose_btn, id=xrc.XRCID('choose_btn'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_playsel_btn, id=xrc.XRCID('playsel_btn'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_addplay_btn, id=xrc.XRCID('addplay_btn'))
        self.Bind(wx.EVT_SCROLL, self.OnScroll_slider, id=xrc.XRCID('slider'))
        self.Bind(wx.EVT_SCROLL, self.OnScroll_slider, id=xrc.XRCID('slider'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_prev_btn, id=xrc.XRCID('prev_btn'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_play_btn, id=xrc.XRCID('play_btn'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_pause_btn, id=xrc.XRCID('pause_btn'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_stop_btn, id=xrc.XRCID('stop_btn'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_next_btn, id=xrc.XRCID('next_btn'))
        self.Bind(wx.EVT_SCROLL, self.OnScroll_volume_sl, id=xrc.XRCID('volume_sl'))
        self.Bind(wx.EVT_SCROLL, self.OnScroll_volume_sl, id=xrc.XRCID('volume_sl'))

#!XRCED:begin-block:xrcemptyorch_frame.OnMenu_open_menu
    def OnMenu_open_menu(self, evt):
        # Replace with event handler code
        print "OnMenu_open_menu()"
#!XRCED:end-block:xrcemptyorch_frame.OnMenu_open_menu        

#!XRCED:begin-block:xrcemptyorch_frame.OnButton_choose_btn
    def OnButton_choose_btn(self, evt):
        # Replace with event handler code
        print "OnButton_choose_btn()"
#!XRCED:end-block:xrcemptyorch_frame.OnButton_choose_btn        

#!XRCED:begin-block:xrcemptyorch_frame.OnButton_playsel_btn
    def OnButton_playsel_btn(self, evt):
        # Replace with event handler code
        print "OnButton_playsel_btn()"
#!XRCED:end-block:xrcemptyorch_frame.OnButton_playsel_btn        

#!XRCED:begin-block:xrcemptyorch_frame.OnButton_addplay_btn
    def OnButton_addplay_btn(self, evt):
        # Replace with event handler code
        print "OnButton_addplay_btn()"
#!XRCED:end-block:xrcemptyorch_frame.OnButton_addplay_btn        

#!XRCED:begin-block:xrcemptyorch_frame.OnScroll_slider
    def OnScroll_slider(self, evt):
        # Replace with event handler code
        print "OnScroll_slider()"
#!XRCED:end-block:xrcemptyorch_frame.OnScroll_slider        

#!XRCED:begin-block:xrcemptyorch_frame.OnScroll_slider
    def OnScroll_slider(self, evt):
        # Replace with event handler code
        print "OnScroll_slider()"
#!XRCED:end-block:xrcemptyorch_frame.OnScroll_slider        

#!XRCED:begin-block:xrcemptyorch_frame.OnButton_prev_btn
    def OnButton_prev_btn(self, evt):
        # Replace with event handler code
        print "OnButton_prev_btn()"
#!XRCED:end-block:xrcemptyorch_frame.OnButton_prev_btn        

#!XRCED:begin-block:xrcemptyorch_frame.OnButton_play_btn
    def OnButton_play_btn(self, evt):
        # Replace with event handler code
        print "OnButton_play_btn()"
#!XRCED:end-block:xrcemptyorch_frame.OnButton_play_btn        

#!XRCED:begin-block:xrcemptyorch_frame.OnButton_pause_btn
    def OnButton_pause_btn(self, evt):
        # Replace with event handler code
        print "OnButton_pause_btn()"
#!XRCED:end-block:xrcemptyorch_frame.OnButton_pause_btn        

#!XRCED:begin-block:xrcemptyorch_frame.OnButton_stop_btn
    def OnButton_stop_btn(self, evt):
        # Replace with event handler code
        print "OnButton_stop_btn()"
#!XRCED:end-block:xrcemptyorch_frame.OnButton_stop_btn        

#!XRCED:begin-block:xrcemptyorch_frame.OnButton_next_btn
    def OnButton_next_btn(self, evt):
        # Replace with event handler code
        print "OnButton_next_btn()"
#!XRCED:end-block:xrcemptyorch_frame.OnButton_next_btn        

#!XRCED:begin-block:xrcemptyorch_frame.OnScroll_volume_sl
    def OnScroll_volume_sl(self, evt):
        # Replace with event handler code
        print "OnScroll_volume_sl()"
#!XRCED:end-block:xrcemptyorch_frame.OnScroll_volume_sl        

#!XRCED:begin-block:xrcemptyorch_frame.OnScroll_volume_sl
    def OnScroll_volume_sl(self, evt):
        # Replace with event handler code
        print "OnScroll_volume_sl()"
#!XRCED:end-block:xrcemptyorch_frame.OnScroll_volume_sl        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('emptyorch.xrc')
