#!/bin/sh

EODIR=$(python -c "from emptyorchestra import emptyorch; import os; print os.path.dirname(emptyorch.__file__)")
ORIGDIR=$(pwd)

echo "EODIR $EODIR"

cd ${EODIR}
python emptyorch.py
cd ${ORIGDIR} 
